using static Macaron.Delegation.Tests.Helper;

using Macaron.InterfaceDelegation;
using Macaron.MemberExposure;

namespace Macaron.Delegation.Tests;

[TestFixture]
public sealed class ImplementExistingMemberTests
{
    [Test]
    public void GeneratesExplicitDelegation_EvenIfImplicitExists_When_UsingDefaultMode()
    {
        AssertGeneratedCode(
            sourceCode:
            """
            namespace Macaron.Delegation.Tests;
            using Macaron.InterfaceDelegation;

            public interface IFoo
            {
                void MethodA();

                void MethodB();
            }

            public class FooImpl : IFoo
            {
                public void MethodA() { }

                public void MethodB() { }
            }

            public partial class TestPartialDefaultImplicit : IFoo
            {
                [Implement(typeof(IFoo))]
                private readonly IFoo _impl = new FooImpl();

                public void MethodA() { }
            }
            """,
            expected:
            """
            // <auto-generated />
            #nullable enable

            namespace Macaron.Delegation.Tests
            {
                partial class TestPartialDefaultImplicit
                {
                    #region global::Macaron.Delegation.Tests.IFoo
                    void global::Macaron.Delegation.Tests.IFoo.MethodA()
                        => _impl.MethodA();

                    void global::Macaron.Delegation.Tests.IFoo.MethodB()
                        => _impl.MethodB();
                    #endregion
                }
            }

            """
        );
    }

    [Test]
    public void SkipsAlreadyImplementedExplicitMembers_When_UsingDefaultMode()
    {
        AssertGeneratedCode(
            sourceCode:
            """
            namespace Macaron.Delegation.Tests;
            using Macaron.InterfaceDelegation;

            public interface IFoo
            {
                void MethodA();

                void MethodB();
            }

            public class FooImpl : IFoo
            {
                public void MethodA() { }

                public void MethodB() { }
            }

            public partial class TestPartialDefaultExplicit : IFoo
            {
                [Implement(typeof(IFoo))]
                private readonly IFoo _impl = new FooImpl();

                void IFoo.MethodA() { }
            }
            """,
            expected:
            """
            // <auto-generated />
            #nullable enable

            namespace Macaron.Delegation.Tests
            {
                partial class TestPartialDefaultExplicit
                {
                    #region global::Macaron.Delegation.Tests.IFoo
                    void global::Macaron.Delegation.Tests.IFoo.MethodB()
                        => _impl.MethodB();
                    #endregion
                }
            }

            """
        );
    }

    [Test]
    public void GeneratesFullDelegation_When_UsingImplicitMode()
    {
        AssertGeneratedCode(
            sourceCode:
            """
            namespace Macaron.Delegation.Tests;
            using Macaron.InterfaceDelegation;

            public interface IFoo
            {
                void MethodA();

                void MethodB();
            }

            public class FooImpl : IFoo
            {
                public void MethodA() { }

                public void MethodB() { }
            }

            public partial class TestPartialImplicit : IFoo
            {
                [Implement(typeof(IFoo), Mode = ImplementationMode.Implicit)]
                private readonly IFoo _impl = new FooImpl();
            }
            """,
            expected:
            """
            // <auto-generated />
            #nullable enable

            namespace Macaron.Delegation.Tests
            {
                partial class TestPartialImplicit
                {
                    #region global::Macaron.Delegation.Tests.IFoo
                    public void MethodA()
                        => _impl.MethodA();

                    public void MethodB()
                        => _impl.MethodB();
                    #endregion
                }
            }

            """
        );
    }

    [Test]
    public void SkipsAlreadyImplementedImplicitMembers_When_UsingImplicitMode()
    {
        AssertGeneratedCode(
            sourceCode:
            """
            namespace Macaron.Delegation.Tests;
            using Macaron.InterfaceDelegation;

            public interface IFoo
            {
                void MethodA();

                void MethodB();
            }

            public class FooImpl : IFoo
            {
                public void MethodA() { }

                public void MethodB() { }
            }

            public partial class TestPartialImplicit : IFoo
            {
                [Implement(typeof(IFoo), Mode = ImplementationMode.Implicit)]
                private readonly IFoo _impl = new FooImpl();

                public void MethodA() { }
            }
            """,
            expected:
            """
            // <auto-generated />
            #nullable enable

            namespace Macaron.Delegation.Tests
            {
                partial class TestPartialImplicit
                {
                    #region global::Macaron.Delegation.Tests.IFoo
                    public void MethodB()
                        => _impl.MethodB();
                    #endregion
                }
            }

            """
        );
    }

    [Test]
    public void SkipsAlreadyImplementedExplicitMembers_When_UsingImplicitMode()
    {
        AssertGeneratedCode(
            sourceCode:
            """
            namespace Macaron.Delegation.Tests;
            using Macaron.InterfaceDelegation;

            public interface IFoo
            {
                void MethodA();

                void MethodB();
            }

            public class FooImpl : IFoo
            {
                public void MethodA() { }

                public void MethodB() { }
            }

            public partial class TestPartialImplicit : IFoo
            {
                [Implement(typeof(IFoo), Mode = ImplementationMode.Implicit)]
                private readonly IFoo _impl = new FooImpl();

                void IFoo.MethodA() { }
            }
            """,
            expected:
            """
            // <auto-generated />
            #nullable enable

            namespace Macaron.Delegation.Tests
            {
                partial class TestPartialImplicit
                {
                    #region global::Macaron.Delegation.Tests.IFoo
                    public void MethodB()
                        => _impl.MethodB();
                    #endregion
                }
            }

            """
        );
    }

    [Test]
    public void GeneratesExplicitDelegation_When_UsingExplicitMode()
    {
        AssertGeneratedCode(
            sourceCode:
            """
            namespace Macaron.Delegation.Tests;
            using Macaron.InterfaceDelegation;

            public interface IService
            {
                void Execute();
            }

            public class ServiceImpl : IService
            {
                public void Execute() { }
            }

            public partial class TestExplicitMode : IService
            {
                [Implement(typeof(IService), Mode = ImplementationMode.Explicit)]
                private readonly IService _impl = new ServiceImpl();
            }
            """,
            expected:
            """
            // <auto-generated />
            #nullable enable

            namespace Macaron.Delegation.Tests
            {
                partial class TestExplicitMode
                {
                    #region global::Macaron.Delegation.Tests.IService
                    void global::Macaron.Delegation.Tests.IService.Execute()
                        => _impl.Execute();
                    #endregion
                }
            }

            """
        );
    }

    [Test]
    public void SkipsAlreadyImplementedExplicitMembers_When_UsingExplicitMode()
    {
        AssertGeneratedCode(
            sourceCode:
            """
            namespace Macaron.Delegation.Tests;
            using Macaron.InterfaceDelegation;

            public interface IFoo
            {
                void MethodA();

                void MethodB();
            }

            public class FooImpl : IFoo
            {
                public void MethodA() { }

                public void MethodB() { }
            }

            public partial class TestPartialExplicit : IFoo
            {
                [Implement(typeof(IFoo), Mode = ImplementationMode.Explicit)]
                private readonly IFoo _impl = new FooImpl();

                void IFoo.MethodA() { }
            }
            """,
            expected:
            """
            // <auto-generated />
            #nullable enable

            namespace Macaron.Delegation.Tests
            {
                partial class TestPartialExplicit
                {
                    #region global::Macaron.Delegation.Tests.IFoo
                    void global::Macaron.Delegation.Tests.IFoo.MethodB()
                        => _impl.MethodB();
                    #endregion
                }
            }

            """
        );
    }

    [Test]
    public void GeneratesExplicitDelegation_EvenIfImplicitExists()
    {
        AssertGeneratedCode(
            sourceCode:
            """
            namespace Macaron.Delegation.Tests;
            using Macaron.InterfaceDelegation;

            public interface IFoo
            {
                void MethodA();

                void MethodB();
            }

            public class FooImpl : IFoo
            {
                public void MethodA() { }

                public void MethodB() { }
            }

            public partial class TestPartialExplicit : IFoo
            {
                [Implement(typeof(IFoo), Mode = ImplementationMode.Explicit)]
                private readonly IFoo _impl = new FooImpl();

                public void MethodA() { }
            }
            """,
            expected:
            """
            // <auto-generated />
            #nullable enable

            namespace Macaron.Delegation.Tests
            {
                partial class TestPartialExplicit
                {
                    #region global::Macaron.Delegation.Tests.IFoo
                    void global::Macaron.Delegation.Tests.IFoo.MethodA()
                        => _impl.MethodA();

                    void global::Macaron.Delegation.Tests.IFoo.MethodB()
                        => _impl.MethodB();
                    #endregion
                }
            }

            """
        );
    }

    [Test]
    public void SkipsAbstractMembers_InSameClass_When_GeneratingDelegation()
    {
        AssertGeneratedCode(
            sourceCode:
            """
            namespace Macaron.Delegation.Tests;
            using Macaron.InterfaceDelegation;

            public interface IAbstractExample
            {
                int GetAnswer();

                void DoSomething();
            }

            public class AbstractExampleImpl : IAbstractExample
            {
                public int GetAnswer() => 42;

                public void DoSomething() { }
            }

            public abstract partial class TestAbstractDelegation : IAbstractExample
            {
                [Implement(typeof(IAbstractExample), Mode = ImplementationMode.Implicit)]
                private readonly IAbstractExample _impl = new AbstractExampleImpl();

                public abstract int GetAnswer();
            }
            """,
            expected:
            """
            // <auto-generated />
            #nullable enable

            namespace Macaron.Delegation.Tests
            {
                partial class TestAbstractDelegation
                {
                    #region global::Macaron.Delegation.Tests.IAbstractExample
                    public void DoSomething()
                        => _impl.DoSomething();
                    #endregion
                }
            }

            """
        );
    }

    [Test]
    public void GeneratesOverride_ForAbstractMembers_InBaseClass()
    {
        AssertGeneratedCode(
            sourceCode:
            """
            namespace Macaron.Delegation.Tests;
            using Macaron.InterfaceDelegation;

            public interface IAbstractExample
            {
                int GetAnswer();

                int Value { get; }
            }

            public class AbstractExampleImpl : IAbstractExample
            {
                public int GetAnswer() => 42;

                public int Value { get => 42; }
            }

            public abstract class TestAbstractDelegationBase
            {
                public abstract int GetAnswer();

                public abstract int Value { get; }
            }

            public partial class TestAbstractDelegation : TestAbstractDelegationBase, IAbstractExample
            {
                [Implement(typeof(IAbstractExample), Mode = ImplementationMode.Implicit)]
                private readonly IAbstractExample _impl = new AbstractExampleImpl();
            }
            """,
            expected:
            """
            // <auto-generated />
            #nullable enable

            namespace Macaron.Delegation.Tests
            {
                partial class TestAbstractDelegation
                {
                    #region global::Macaron.Delegation.Tests.IAbstractExample
                    public override int GetAnswer()
                        => _impl.GetAnswer();

                    public override int Value
                    {
                        get => _impl.Value;
                    }
                    #endregion
                }
            }

            """
        );
    }

    [Test]
    public void SkipsOverriddenMembers_InCurrentClass_When_GeneratingDelegation()
    {
        AssertGeneratedCode(
            sourceCode:
            """
            namespace Macaron.Delegation.Tests;
            using Macaron.InterfaceDelegation;

            public interface IAbstractExample
            {
                int GetAnswer();

                void DoSomething();

                int Value { get; }
            }

            public class AbstractExampleImpl : IAbstractExample
            {
                public int GetAnswer() => 42;

                public void DoSomething() { }

                public int Value { get => 42; }
            }

            public abstract class TestAbstractDelegationBase
            {
                public abstract int GetAnswer();

                public abstract int Value { get; }
            }

            public partial class TestAbstractDelegation : TestAbstractDelegationBase
            {
                [Implement(typeof(IAbstractExample), Mode = ImplementationMode.Implicit)]
                private readonly IAbstractExample _impl = new AbstractExampleImpl();

                public override int GetAnswer() => 42;

                public override int Value { get => 42; }
            }
            """,
            expected:
            """
            // <auto-generated />
            #nullable enable

            namespace Macaron.Delegation.Tests
            {
                partial class TestAbstractDelegation
                {
                    #region global::Macaron.Delegation.Tests.IAbstractExample
                    public void DoSomething()
                        => _impl.DoSomething();
                    #endregion
                }
            }

            """
        );
    }
}
